stages:
  - stage: InstallDependencies
    displayName: "Install dependencies"
    jobs:
      - job: InstallDependencies
        steps:
        - script: |
            python3 -m pip install -r requirements.txt
          displayName: "Install dependencies"
        - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      
        - name: Install dependencies
        run: pip install -r requirements.txt
        
        - name: Install Node Modules
        run: |
          cd frontend
          npm install

        - name: Build Frontend
        run: |
          cd frontend
          npm run build
          cd ..

# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

# name: Build and deploy Python app to Azure Web App - formacion-cloud

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
  
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Python version
#         uses: actions/setup-python@v1
#         with:
#           python-version: '3.10'

#       - name: Create and start virtual environment
#         run: |
#           python -m venv venv
#           source venv/bin/activate
      
#       - name: Install dependencies
#         run: pip install -r requirements.txt
        
#       # Optional: Add step to run tests here (PyTest, Django test suites, etc.)

#       - name: Zip artifact for deployment
#         run: zip release.zip ./* -r

#       - name: Upload artifact for deployment jobs
#         uses: actions/upload-artifact@v3
#         with:
#           name: python-app
#           path: |
#             release.zip
#             !venv/

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   environment:
  #     name: 'Production'
  #     url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: python-app

  #     - name: Unzip artifact for deployment
  #       run: unzip release.zip

      
  #     - name: 'Deploy to Azure Web App'
  #       uses: azure/webapps-deploy@v2
  #       id: deploy-to-webapp
  #       with:
  #         app-name: 'formacion-cloud'
  #         slot-name: 'Production'
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_139B9D66D3154E4E91B23E9EEE1FC156 }}
